# Generated by Django 3.2.19 on 2023-05-25 14:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('victoriabakeryblog', '0003_auto_20230520_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipepost',
            name='hearts',
            field=models.ManyToManyField(blank=True, related_name='blogpost_hearts', to=settings.AUTH_USER_MODEL),
        ),
    ]
