# Generated by Django 3.2.19 on 2023-05-25 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('victoriabakeryblog', '0005_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
