# Generated by Django 3.2.19 on 2023-05-25 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('victoriabakeryblog', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
