# Generated by Django 3.2.19 on 2023-05-30 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('victoriabakeryblog', '0010_tip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercomment',
            name='email',
        ),
        migrations.DeleteModel(
            name='Tip',
        ),
    ]
