# Generated by Django 3.2.19 on 2023-05-30 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('victoriabakeryblog', '0012_tipcomments_tips'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tips',
            old_name='tslug',
            new_name='slug',
        ),
    ]
