# Generated by Django 3.2.19 on 2023-06-05 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('victoriabakeryblog', '0013_rename_tslug_tips_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipcomments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tcomments', to='victoriabakeryblog.tips'),
        ),
    ]
